# -*- coding: utf-8 -*-

DEFAULT_DS_CONFIG = {
    "train_batch_size": 1,
    "gradient_accumulation_steps": 1,
    "zero_allow_untested_optimizer": True,
    "zero_force_ds_cpu_optimizer": True,
    "optimizer": {
        "type": "Adam",
        "params": {
            "lr": 0.00002,
            "betas": [0.9, 0.999],
            "eps": 1e-8,
            "weight_decay": 0.0,
        },
    },
    "scheduler": {
        "type": "WarmupDecayLR",
        "params": {
            "warmup_type": "linear",
            "total_num_steps": 1000000,
            "warmup_max_lr": 0.00002,
            "warmup_num_steps": 60000,
        },
    },
    "zero_optimization": {
        "stage": 1,
        "allgather_partitions": True,
        "allgather_bucket_size": 5e8,
        "overlap_comm": False,
        "reduce_scatter": False,
        "reduce_bucket_size": "auto",
        "contiguous_gradients": False,
        "offload_optimizer": {
            "device": "none",
            "nvme_path": ".",
            "pin_memory": False,
            "ratio": 1.0,
            "buffer_count": 4,
            "fast_init": False,
        },
        "offload_param": {
            "device": "none",
            "nvme_path": ".",
            "pin_memory": False,
            "buffer_count": 5,
            "buffer_size": 1e8,
            "max_in_cpu": 1e9,
        },
        "stage3_max_live_parameters": 1e9,
        "stage3_max_reuse_distance": 1e9,
        "stage3_prefetch_bucket_size": "auto",
        "stage3_param_persistence_threshold": "auto",
        "sub_group_size": 1e12,
        "elastic_checkpoint": False,
        "stage3_gather_16bit_weights_on_model_save": False,
        "ignore_unused_parameters": True,
        "round_robin_gradients": False,
        "zero_hpz_partition_size": 1,
        "zero_quantized_weights": False,
        "zero_quantized_gradients": False,
    },
    "aio": {
        "block_size": 1048576,
        "queue_depth": 8,
        "thread_count": 1,
        "single_submit": False,
        "overlap_events": True,
        "ignore_unused_parameters": True,
    },
    "fp16": {
        "enabled": False,
        "auto_cast": False,
        "loss_scale": 0,
        "initial_scale_power": 16,
        "loss_scale_window": 1000,
        "hysteresis": 2,
        "consecutive_hysteresis": False,
        "min_loss_scale": 0.001,
    },
    "bf16": {"enabled": False},
    "amp": {
        "enabled": False,
        "opt_level": "O1",
    },
    "gradient_clipping": 1.0,
    "activation_checkpointing": {
        "partition_activations": False,
        "cpu_checkpointing": False,
        "contiguous_memory_optimization": False,
        "number_checkpoints": None,
        "synchronize_checkpoint_boundary": False,
        "profile": False,
    },
    "wandb": {
        "enabled": False,
        "team": "yourteam",
        "group": "yourgroup",
        "project": "yourproject",
    },
    "flops_profiler": {
        "enabled": False,
        "profile_step": 10,
        "module_depth": -1,
        "top_modules": 1,
        "detailed": True,
        "output_file": None,
    },
    "steps_per_print": 100,
    "memory_breakdown": False,
    "wall_clock_breakdown": False,
    "comms_logger": {
        "enabled": False,
        "verbose": False,
        "prof_all": True,
        "debug": False,
        "prof_ops": ["all_reduce", "all_gather"],
    },
}
